"""initial_schema_postgres

Revision ID: 0c53e70b434a
Revises: 
Create Date: 2026-04-10 06:26:35.248015

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c53e70b434a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_is_active'), 'announcement', ['is_active'], unique=False)
    op.create_table('season',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemconfig',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tournamentevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dominant_hand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rubber_forehand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rubber_backhand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('global_mmr', sa.Float(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_oauth_id'), 'user', ['oauth_id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_a_p1_id', sa.Uuid(), nullable=False),
    sa.Column('team_a_p2_id', sa.Uuid(), nullable=True),
    sa.Column('team_b_p1_id', sa.Uuid(), nullable=False),
    sa.Column('team_b_p2_id', sa.Uuid(), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('mmr_exchanged', sa.Float(), nullable=False),
    sa.Column('lp_exchanged', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=False),
    sa.Column('season_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_a_p1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_a_p2_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_b_p1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_b_p2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_season_id'), 'match', ['season_id'], unique=False)
    op.create_index(op.f('ix_match_status'), 'match', ['status'], unique=False)
    op.create_table('playerstathistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mmr', sa.Float(), nullable=False),
    sa.Column('season_lp', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstathistory_recorded_at'), 'playerstathistory', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_playerstathistory_user_id'), 'playerstathistory', ['user_id'], unique=False)
    op.create_table('seasonprize',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonprize_season_id'), 'seasonprize', ['season_id'], unique=False)
    op.create_table('seasonrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season_lp', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonrecord_season_id'), 'seasonrecord', ['season_id'], unique=False)
    op.create_index(op.f('ix_seasonrecord_user_id'), 'seasonrecord', ['user_id'], unique=False)
    op.create_table('tournamentparticipant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournamentevent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournamentparticipant_tournament_id'), 'tournamentparticipant', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_tournamentparticipant_user_id'), 'tournamentparticipant', ['user_id'], unique=False)
    op.create_table('matchparticipation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('mmr_delta', sa.Float(), nullable=False),
    sa.Column('lp_delta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchparticipation_match_id'), 'matchparticipation', ['match_id'], unique=False)
    op.create_index(op.f('ix_matchparticipation_user_id'), 'matchparticipation', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_matchparticipation_user_id'), table_name='matchparticipation')
    op.drop_index(op.f('ix_matchparticipation_match_id'), table_name='matchparticipation')
    op.drop_table('matchparticipation')
    op.drop_index(op.f('ix_tournamentparticipant_user_id'), table_name='tournamentparticipant')
    op.drop_index(op.f('ix_tournamentparticipant_tournament_id'), table_name='tournamentparticipant')
    op.drop_table('tournamentparticipant')
    op.drop_index(op.f('ix_seasonrecord_user_id'), table_name='seasonrecord')
    op.drop_index(op.f('ix_seasonrecord_season_id'), table_name='seasonrecord')
    op.drop_table('seasonrecord')
    op.drop_index(op.f('ix_seasonprize_season_id'), table_name='seasonprize')
    op.drop_table('seasonprize')
    op.drop_index(op.f('ix_playerstathistory_user_id'), table_name='playerstathistory')
    op.drop_index(op.f('ix_playerstathistory_recorded_at'), table_name='playerstathistory')
    op.drop_table('playerstathistory')
    op.drop_index(op.f('ix_match_status'), table_name='match')
    op.drop_index(op.f('ix_match_season_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tournamentevent')
    op.drop_table('systemconfig')
    op.drop_table('season')
    op.drop_index(op.f('ix_announcement_is_active'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
