"""add event_type to history

Revision ID: 316cf9b54541
Revises: ca79d8a55e64
Create Date: 2026-04-11 08:23:09.841015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '316cf9b54541'
down_revision: Union[str, Sequence[str], None] = 'ca79d8a55e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerstathistory', sa.Column('match_id', sa.Uuid(), nullable=True))
    op.add_column('playerstathistory', sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'playerstathistory', 'match', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playerstathistory', type_='foreignkey')
    op.drop_column('playerstathistory', 'event_type')
    op.drop_column('playerstathistory', 'match_id')
    # ### end Alembic commands ###
